version: "3.8"
services:
  keycloak-daps:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '8888:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    volumes:
      - keycloak:/opt/keycloak/data
    command:
      - start-dev

  sovity-daps:
    image: ghcr.io/sovity/sovity-daps:sha-32a3033
    ports:
      - '9443:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    volumes:
      - keycloak2:/opt/keycloak/data
    command:
      - start-dev

  edc-ui:
    image: ghcr.io/sovity/edc-ui:3.2.2
    ports:
      - '11000:8080'
    environment:
      - EDC_UI_CATALOG_URLS=
      - EDC_UI_ACTIVE_PROFILE=mds-open-source
      - EDC_UI_CONFIG_URL=edc-ui-config
      - EDC_UI_MANAGEMENT_API_URL=http://localhost:11002/api/management
      - EDC_UI_MANAGEMENT_API_KEY=12345

  edc:
    image: ghcr.io/sovity/edc-ce-mds:8.1.0
    depends_on:
      - postgresql
    environment:
      EDC_OAUTH_TOKEN_URL: http://keycloak-daps:8080/realms/DAPS/protocol/openid-connect/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://keycloak-daps:8080/realms/DAPS/protocol/openid-connect/certs
      EDC_OAUTH_CLIENT_ID: B6:44:08:FC:F5:12:0F:61:C2:20:49:A2:C4:2F:4E:08:D6:D5:B4:9F:keyid:38:35:5D:24:42:BB:4B:32:58:C2:72:C6:CF:4E:04:04:1B:6F:26:77
      MY_EDC_PARTICIPANT_ID: http://connector1:11002
      
      EDC_KEYSTORE: "/keystore.jks"
      EDC_KEYSTORE_PASSWORD: 'password'
      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
    
      MY_EDC_TITLE: "MDS EDC Connector 1"
      MY_EDC_DESCRIPTION: "MDS EDC Connector"
      MY_EDC_CURATOR_URL: "https://example.com"
      MY_EDC_CURATOR_NAME: "Example GmbH"
      MY_EDC_MAINTAINER_URL: "https://sovity.de"
      MY_EDC_MAINTAINER_NAME: "sovity GmbH"

      MY_EDC_FQDN: "edc"
      EDC_API_AUTH_KEY: 12345

      MY_EDC_JDBC_URL: jdbc:postgresql://postgresql:5432/edc
      MY_EDC_JDBC_USER: edc
      MY_EDC_JDBC_PASSWORD: edc

      MY_EDC_PROTOCOL: "http://"
      EDC_DSP_CALLBACK_ADDRESS: http://edc:11003/api/dsp
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,X-Api-Key'
      EDC_WEB_REST_CORS_ORIGINS: '*'

      EDC_LOGGINGHOUSE_EXTENSION_URL: https://clearing-next.test.mobility-dataspace.eu
      EDC_LOGGINGHOUSE_EXTENSION_ENABLED: 'false'
    ports:
      - '11001:11001'
      - '11002:11002'
      - '11003:11003'
      - '11004:11004'
      - '11005:5005'
    volumes:
      - ./keystore.jks:/keystore.jks

  postgresql:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    volumes:
      - postgresql:/bitnami/postgresql

  edc-ui2:
    image: ghcr.io/sovity/edc-ui:3.2.2
    ports:
      - '12000:8080'
    environment:
      - EDC_UI_CATALOG_URLS=
      - EDC_UI_ACTIVE_PROFILE=mds-open-source
      - EDC_UI_CONFIG_URL=edc-ui-config
      - EDC_UI_MANAGEMENT_API_URL=http://localhost:12002/api/management
      - EDC_UI_MANAGEMENT_API_KEY=ApiKeyDefaultValue

  edc2:
    image: ghcr.io/sovity/edc-ce-mds:8.1.0
    depends_on:
      - postgresql2
    environment:
      EDC_OAUTH_TOKEN_URL: http://keycloak-daps:8080/realms/DAPS/protocol/openid-connect/token
      EDC_OAUTH_PROVIDER_JWKS_URL: http://keycloak-daps:8080/realms/DAPS/protocol/openid-connect/certs
      EDC_OAUTH_CLIENT_ID: B6:44:08:FC:F5:12:0F:61:C2:20:49:A2:C4:2F:4E:08:D6:D5:B4:9F:keyid:38:35:5D:24:42:BB:4B:32:58:C2:72:C6:CF:4E:04:04:1B:6F:26:77
      MY_EDC_PARTICIPANT_ID: http://connector2:12002
      
      EDC_KEYSTORE: "/keystore.jks"
      EDC_KEYSTORE_PASSWORD: 'password'
      EDC_OAUTH_CERTIFICATE_ALIAS: 1
      EDC_OAUTH_PRIVATE_KEY_ALIAS: 1
    
      MY_EDC_TITLE: "MDS EDC Connector 2"
      MY_EDC_DESCRIPTION: "MDS EDC Connector"
      MY_EDC_CURATOR_URL: "https://example.com"
      MY_EDC_CURATOR_NAME: "Example GmbH"
      MY_EDC_MAINTAINER_URL: "https://sovity.de"
      MY_EDC_MAINTAINER_NAME: "sovity GmbH"

      MY_EDC_FQDN: "edc2"
      EDC_API_AUTH_KEY: ApiKeyDefaultValue

      MY_EDC_JDBC_URL: jdbc:postgresql://postgresql2:5432/edc
      MY_EDC_JDBC_USER: edc
      MY_EDC_JDBC_PASSWORD: edc

      MY_EDC_PROTOCOL: "http://"
      EDC_DSP_CALLBACK_ADDRESS: http://edc2:12003/api/dsp
      EDC_WEB_REST_CORS_ENABLED: 'true'
      EDC_WEB_REST_CORS_HEADERS: 'origin,content-type,accept,authorization,X-Api-Key'
      EDC_WEB_REST_CORS_ORIGINS: '*'

      EDC_LOGGINGHOUSE_EXTENSION_URL: https://clearing-next.test.mobility-dataspace.eu
      EDC_LOGGINGHOUSE_EXTENSION_ENABLED: 'false'
    ports:
      - '12001:11001'
      - '12002:11002'
      - '12003:11003'
      - '12004:11004'
      - '12005:5005'
    volumes:
      - ./keystore.jks:/keystore.jks

  postgresql2:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    volumes:
      - postgresql2:/bitnami/postgresql

volumes:
  keycloak:
  keycloak2:
  postgresql:
  postgresql2: